### ISSUE TITLE
Consecutive/Multiple Delimiters?

### ISSUE THREAD

**Issue by flying-tiger** [Shot511/strutil#2]
This looks great; thank you for making it available. I go back and forth between C++ and Python and hate having to do string ops in C++. Quick question... does this support (1) splitting on multiple delimiters and (2) treating consecutive delimiters as one? Quick look suggests no, but wanted to ask.

**Comment by flying-tiger** [comment]
Corollary: Are you open to a pull request adding this feature? I'm thinking something like:
```cpp
std::vector<std::string> multi_split(const std::string& str, const std::string& delims, bool collapse = true);
```

**Comment by Shot511** [comment]
Sure, go ahead! If you write a working algorithm and test(s) for it, I'll merge your code into the code base :) Otherwise, I'll probably write my own implementation of this, but this could happen in ~3 weeks (best case scenario).

**Comment by flying-tiger** [comment]
While implementing this, I'm noticing as few inconsistencies in the semantics of `split` for char and str inputs:

**Empty string handling**
Splitting on an empty string results in different output depending on delimiter type:
```cpp 
split("", ';').size()  == 0; // split return []
split("", ">=").size() == 1; // split returns [""]
```
I'm inclined to the second approach, as in python:
```python
"".split(";') == [""] // True
```

**Trailing Delimiter Handling**
Splitting strings with trailing delimiters returns different results:
```cpp
split("abc;", ';').size()  == 1;  // split returns ["abc"]
split("abc>=", ">=").size == 2; // split returns ["abc", ""]
```
Again, python favors the latter:
```python
"abc;".split(";") == ["abc", ""] // True
```


Thoughts? I'm thinking I'll adjust the char-splitting version to match python semantics.

**Comment by Shot511** [comment]
Sure, make char versions to match string versions - these functions should have the same output not to mislead the end user. You can also add additional tests to [tests/test_cases.cpp](https://github.com/Shot511/strutil/blob/master/tests/test_cases.cpp). I appreciate your contribution! :)
